### ISSUE TITLE
No access to other Form Elements from BaseValidator

### ISSUE THREAD

**Issue by KuroThing** [Q42/vue-dotnet-validator#2]
I would love to be able to use this set of components, despite the fact that it doesn't cover all possible validation cases that the default unobtrusive validator does. So i decided to write some basic validators that would provide similar experiences.

The first one i decided to write was "Equal To Other", or using the .Net attributes `[Compare]`. To do this i would need access to the current input element, or at least the default html attributes that are not prefixed by `data-`, along with the ability retrieve other form input members to compare their values.

**Comment by tdekoning** [comment]
Thanks for your feedback!

I guess it would be possible to implement a validator like that. It would require some changes to the `validator-group`, `validator` and the `basevalidator` class in order to work.
I think that if we make it possible to expose the `name` property of the input element on the `validator` vue component and add a `findByName` method on the `validator-group` AND pass the `validator-group` to the `basevalidator` instance through the constructor, we'd have all the wiring we need. 

I can imagine the `CompareValidator` class to look a little like this:
```
class CompareValidator extends BaseValidator {
    constructor(message, attributes, validatorGroup) {
         super(message, attributes, validatorGroup);
         this.otherField = validatorGroup.findValidatorByName(attributes['valEqualtoOther']);
    }

    isValid(value) {
        return !value || !this.otherField || value == this.otherField.value;
    }
}
```

The `Compare` annotation adds the following attribute `data-val-equalto-other="*.HouseNumber"`, so in this case it can use a wildcard when pointing to another field, so the `findByName` lookup should support wildcards.

Would a solution like that be sufficient for you? Or do you have suggestions on how it would be even better?

**Comment by KuroThing** [comment]
Plenty sufficient.

Although it appears that the `*.` is some sort of Prefix for Models, so i'm not sure if it would be a great idea to turn those into a wildcard within the `findByName` method.

**Comment by tdekoning** [comment]
@KuroThing 
I have had a little bit of time today to work out a solution for this.
It is functional, but not 100% done yet. Any suggestions are welcome!

Pull request: #3

**Comment by KuroThing** [comment]
Thanks you very much!

**Comment by tdekoning** [comment]
You're welcome, thanks for providing feedback!
