### ISSUE TITLE
Blurred state is never reset to false

### ISSUE THREAD

**Issue by KuroThing** [Q42/vue-dotnet-validator#4]
In the `showValidationMessage`, you have a [comment](https://github.com/Q42/vue-dotnet-validator/blob/master/src/validator.js#L115) that says 'Only show validation after blur.', however as it stands the blurred property is never reset to false, so after the first time a field has the blurred event triggered, it will check to see if it is valid on any change to the field.

I'm not sure if this is intended or a slight oversight, so here i am.

**Comment by tdekoning** [comment]
That is intended behaviour, and currently there is no setting that would alter that behaviour.
The idea is that when a user first interacts with the input field, he/she will not immediately be confronted with input errors, because perhaps just the first character has been typed.
Resetting the blur property does not make much sense to me, because if a user sees an error and wants to correct it, it is nice to provide instant feedback.

**Comment by KuroThing** [comment]
That makes sense. I might make myself a slightly modified version that uses `setTimeout` to delay the validation check until the user finishes typing, to reduce potential performance problems that could occur from having a lot of validators / a time consuming validator.
